# Generated by Django 2.2.2 on 2019-06-23 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TpTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('sn_ativo', models.BooleanField(default=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_modificacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('dt_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('CPF', models.CharField(max_length=14)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_modificacao', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('ddd', models.CharField(max_length=3)),
                ('tp_telefone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.TpTelefone')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
            ],
        ),
    ]
