# Generated by Django 2.2.2 on 2019-06-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190630_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='galeria/original'),
        ),
    ]
